stages:
  - build

build-etalert-backend:
  stage: build
  image: docker:latest
  # when: manual
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  before_script:
    - apk add --no-cache qemu-user-static
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    - docker buildx create --use
  script:
    - chmod +x build-docker-etalert-backend.sh
    - ./build-docker-etalert-backend.sh