stages:
  - build

build-etalert-backend:
  stage: build
  needs:
    - job: etalert-backend
  image: docker:latest
  # when: manual
  services:
    - docker:dind
  script:
    - ./build-docker-etalert-backend.sh