stages:
  - build

build-etalert-backend:
  stage: build
  image: docker:latest
  # when: manual
  services:
    - docker:dind
  script:
    - chmod +x build-docker-etalert-backend.sh
    - ./build-docker-etalert-backend.sh